### ISSUE TITLE
Error for V1.1.0?

### ISSUE THREAD

**Issue by liuhx9988** [lscyane/KCV_LoggerPlugin#2]
I can use 1.0.0 without any problem.
Sorry for the English 

1) Could not load file or assembly 'file:///C:\Users\liuhx\Desktop\KanColleViewer ver.4.2\Xceed.Wpf.Toolkit.dll' or one of its dependencies. The system cannot find the file specified.

Resulting in: The type initializer for 'KCVLoggerPlugin.LoggerPlugin' threw an exception.

Resulting in: An exception occurred while trying to create an instance of type 'KCVLoggerPlugin.LoggerPlugin'.

Resulting in: Cannot activate part 'KCVLoggerPlugin.LoggerPlugin'.
Element: KCVLoggerPlugin.LoggerPlugin -->  KCVLoggerPlugin.LoggerPlugin -->  AssemblyCatalog (Assembly="LoggerPlugin, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null")

Resulting in: Cannot get export 'KCVLoggerPlugin.LoggerPlugin (ContractName="Grabacr07.KanColleViewer.Composition.IPlugin")' from part 'KCVLoggerPlugin.LoggerPlugin'.
Element: KCVLoggerPlugin.LoggerPlugin (ContractName="Grabacr07.KanColleViewer.Composition.IPlugin") -->  KCVLoggerPlugin.LoggerPlugin -->  AssemblyCatalog (Assembly="LoggerPlugin, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null")

   at System.ComponentModel.Composition.Hosting.CompositionServices.GetExportedValueFromComposedPart(ImportEngine engine, ComposablePart part, ExportDefinition definition)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportedValue(CatalogPart part, ExportDefinition export, Boolean isSharedPart)
   at System.ComponentModel.Composition.Primitives.Export.get_Value()
   at System.ComponentModel.Composition.ExportServices.GetCastedExportedValue[T](Export export)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Grabacr07.KanColleViewer.Composition.PluginService.<Load>d__23.MoveNext()

**Comment by lscyane** [comment]
「Xceed.Wpf.Toolkit.dll」をPlugins ディレクトリの中ではなく「KanColleViewer.exe」と同じ階層に置いてみてください。それで解決できるでしょうか？

Please place "Xceed.Wpf.Toolkit.dll" in the same hierarchy as "KanColleViewer.exe", not in the Plugins directory. Can you solve it by doing so?

**Comment by liuhx9988** [comment]
That works for me thx!!!XD
